# For local development only to spin up services to test against
version: "3"
services:
  seaweedfs:
    image: chrislusf/seaweedfs:4.48
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: data,echo-test-data,ooi-raw-data
    ports:
      - 9000:8333
    networks:
      - echopypenetwork
    volumes:
      - echopype_s3data:/data
  httpserver:
    image: httpd:2.4
    ports:
      - 8080:80
    networks:
      - echopypenetwork
networks:
  echopypenetwork:

volumes:
  echopype_s3data:
